version: "3.3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: db
      RAILS_ENV: development
      DB_NAME: chibilinks_api_db
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
